version: '3.8'

services:
  # Servidor web PHP + Apache
  web:
    image: php:8.2-apache
    container_name: cimscat_web
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./logs:/var/log/apache2
      - ./docker/php-custom.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    command: >
      bash -c "
      apt-get update && 
      apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev libwebp-dev zlib1g-dev &&
      docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp &&
      docker-php-ext-install pdo pdo_mysql gd && 
      a2enmod rewrite && 
      apache2-foreground
      "

  # Base de dades MySQL
  db:
    image: mysql:8.0
    container_name: cimscat_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cimscat
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: cimscat_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data: